import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "HOSHIZORA | HONKAI STAR RAIL",
  description: "Generated by Jiranon-K",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="black">
      <body>
        {children}
      </body>
    </html>
  );
}
